In [ ]:
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

In [ ]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

In [ ]:
x = np.array([4, 6, 7, 3, 2])
(x > 3)

In [ ]:
(x > 3).all()

In [ ]:
(x > 3).any()

In [ ]:
(x < 10).any()

In [ ]:
(x < 10).all()

In [ ]:
(x > 10).any()

In [28]:
x = np.array([4, 6, 7, 3, 2])
x > 5

array([False,  True,  True, False, False])

In [29]:
np.where(x>5)

(array([1, 2], dtype=int64),)

In [ ]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20)

In [ ]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

In [ ]:
np.argmax(x)

In [ ]:
np.argmin(x)

In [30]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [31]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [ ]:
x.shape

In [ ]:
cond.shape

In [ ]:
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)
x[cond]

In [ ]:
x.take(cond)

In [32]:
x = np.array([[1,4], [9,16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])

In [33]:
x = np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])