In [72]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [73]:
type(test_array[3])

numpy.float64

In [74]:
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)

[1. 4. 5. 8.]


In [75]:
print(type(test_array[3])) # 실수형(floating Type)으로 자동 형 변환 실시

<class 'numpy.float64'>


In [76]:
print(test_array.dtype) # 배열 전체의 데이터 타입 반환

float64


In [77]:
print(test_array.shape) # 배열의 구조(shape)를 반환함

(4,)


In [78]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [79]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [80]:
tensor_rank3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]] ]
np.array(tensor_rank3, int).ndim

3

In [81]:
np.array(tensor_rank3, int).size

48

In [82]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [84]:
import sys
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

In [85]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

In [86]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [87]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [88]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [123]:
x.reshape(2, 2)

ValueError: cannot reshape array of size 12 into shape (2,2)

In [90]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [91]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [94]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [95]:
x = np.array([[1, 2, 3], [4.5, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
x[0][0]

1

In [97]:
x[0,2]

3

In [98]:
x[0, 1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [99]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:,2:] # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [100]:
x[1,1:3] # 1행의 1열 ~ 2열

array([7, 8])

In [101]:
x[1:3] # 1행 ~ 2행의 전체

array([[ 6,  7,  8,  9, 10]])

In [102]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [104]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [105]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [107]:
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [108]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [109]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [110]:
np.empty(shape=(2,4), dtype=np.float32)

array([[5.7857652e-39, 8.4489539e-39, 5.3265527e-39, 7.8061461e-39],
       [9.2755463e-39, 1.0561242e-38, 1.0744882e-38, 9.2755463e-39]],
      dtype=float32)

In [111]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [113]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [114]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [115]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [116]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [117]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [118]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
np.diag(matrix)

array([0, 4, 8])

In [120]:
np.diag(matrix, k=1)

array([1, 5])

In [124]:
np.random.uniform(0, 5, 10)

array([3.85945911, 3.47716988, 1.67768275, 0.3354801 , 0.2738343 ,
       0.36708778, 0.30588348, 4.72230976, 0.68506257, 4.12521483])

In [125]:
np.random.normal(0, 2, 10)

array([-0.67745458, -2.08733763, -1.16784213,  2.1393218 ,  2.68854843,
        3.45422008,  1.82471791,  3.21004048,  0.56142077, -0.14994878])

In [132]:
np.linspace(0, 1, 5)
bins = np.linspace(-5, 5, 20)
counts = np.zeros_like(bins)
print(counts)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
